version: '3.8'

x-var: &COMMON
  networks:
    internal:

networks:
  internal:

services:
  kaduhiro:
    <<: *COMMON
    build: ../../build
    image: kaduhiro/kaduhiro
    container_name: kaduhiro
    hostname: kaduhiro
    ports:
      - 3000:3000
    volumes:
      - ../..:/app
    command:
      - /bin/sh
      - -c
      - 'yarn && yarn build && yarn export && yarn serve'
